-- MySQL Script generated by MySQL Workbench
-- Sun Sep 11 14:33:47 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jakal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jakal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jakal` DEFAULT CHARACTER SET utf8 ;
USE `jakal` ;

-- -----------------------------------------------------
-- Table `jakal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakal`.`users` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jakal`.`suggestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakal`.`suggestions` (
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(512) NOT NULL,
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `submitted` DATE NULL DEFAULT NULL,
  `user_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `winner` VARCHAR(45) NULL DEFAULT '0',
  `fresh` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `suggestions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jakal`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jakal`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakal`.`votes` (
  `suggestion_id` MEDIUMINT(9) NULL DEFAULT NULL,
  INDEX `suggestion_id_index` (`suggestion_id` ASC),
  CONSTRAINT `votes_ibfk_1`
    FOREIGN KEY (`suggestion_id`)
    REFERENCES `jakal`.`suggestions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
